repos:
  - repo: local
    hooks:
      - id: eslint
        name: ESLint hooks
        description: Check for lint errors
        entry: ./.github/hooks/eslint.sh
        language: script
        types_or: [javascript, jsx, ts, tsx]